import csv

# manual creating of dictionary inside a list with datas for creating a CSV with subject and classmark
subject_classmark_data = [
    {"subject": "Accountancy", "classmark" : "HF"},
    {"subject": "American History", "classmark" : ["E", "F"]},
    {"subject": "American Literature", "classmark" : "PS"},
    {"subject": "Archaeology", "classmark" : "CC"},
    {"subject": "Art", "classmark" : "N"},
    {"subject": "Astrophysics", "classmark" : "QB"},
    {"subject": "Biochemistry", "classmark" : ["QP", "RB"]},
    {"subject": "Biology", "classmark" : "QH"},
    {"subject": "Biomedical Science", "classmark" : ["QR", "RB"]},
    {"subject": "Botany", "classmark" : ["QK", "S"]},
    {"subject": "British History", "classmark" : "DA"},
    {"subject": "Business", "classmark" : ["HD", "HE", "HF"]},
    {"subject": "Chemistry", "classmark" : "QD"},
    {"subject": "Chinese", "classmark" : "PL"},
    {"subject": "Computing", "classmark" : ["QA", "TK"]},
    {"subject": "Counselling and Psychotherapy", "classmark" : "RC"},
    {"subject": "Criminology", "classmark" : "HV"},
    {"subject": "Ecology", "classmark" : "QH"},
    {"subject": "Economics", "classmark" : ["HA","HB","HC","HD","HE","HF","HH","HI","HJ"]},
    {"subject": "Education", "classmark" : "L"},
    {"subject": "English Language", "classmark" : "PE"},
    {"subject": "English Literature", "classmark" : "PR"},
    {"subject": "Environmental Studies", "classmark" : ["GE","GF"]},
    {"subject": "Film Studies", "classmark" : "PN"},
    {"subject": "Finance", "classmark" : ["HG","HH","HI","HJ"]},
    {"subject": "Forensic Science", "classmark" : "HV"},
    {"subject": "French", "classmark" : "PC"},
    {"subject": "Geography", "classmark" : ["G","GA","GB","GC","GD","GE","GF"]},
    {"subject": "Geology and Geoscience", "classmark" : "QE"},
    {"subject": "German", "classmark" : "PF"},
    {"subject": "History", "classmark" : "D"},
    {"subject": "Human Biology", "classmark" : ["QM","QN","QO","QP","QQ","QR"]},
    {"subject": "Human Resource Management", "classmark" : ["HD","HE","HF"]},
    {"subject": "International Law", "classmark" : "JX"},
    {"subject": "International Relations", "classmark" : "JZ"},
    {"subject": "Italian", "classmark" : "PC"},
    {"subject": "Japanese", "classmark" : "PL"},
    {"subject": "Law", "classmark" : "K"},
    {"subject": "Management and Marketing", "classmark" : ["HD","HE","HF"]},
    {"subject": "Mathematics", "classmark" : "QA"},
    {"subject": "Media Studies", "classmark" : "P"},
    {"subject": "Medicinal Chemistry", "classmark" : "QP"},
    {"subject": "Medicine", "classmark" : "R"},
    {"subject": "Mental Health", "classmark" : ["RA","RB","RC"]},
    {"subject": "Music Technology", "classmark" : ["MT","ML"]},
    {"subject": "Neuroscience", "classmark" : "RC"},
    {"subject": "Nursing", "classmark" : "RI"},
    {"subject": "Pharmacology", "classmark" : "RM"},
    {"subject": "Pharmacy", "classmark" : "RS"},
    {"subject": "Philosophy", "classmark" : ["B","BA","BB","BC","BD","BE","BF","BG","BH","BI","BJ"]},
    {"subject": "Physics", "classmark" : "QC"},
    {"subject": "Physiology", "classmark" : "QP"},
    {"subject": "Physiotherapy", "classmark" : "RM"},
    {"subject": "Politics", "classmark" : ["J","JA","JB","JC","JD","JE","JF","JG","JH","JI","JJ","JK","JL","JM","JN","JO","JP","JQ","JR","JS","JT","JU","JV","JW","JX"]},
    {"subject": "Psychology", "classmark" : "BF"},
    {"subject": "Radiography", "classmark" : "RC"},
    {"subject": "Religion", "classmark" : ["BL","BM","BN","BO","BP","BQ","BR","BS","BT","BU","BV","BW","BX"]},
    {"subject": "Russian", "classmark" : "PG"},
    {"subject": "Social Work", "classmark" : "HV"},
    {"subject": "Sociology", "classmark" : ["HM","HN","HO","HP","HQ","HR","HS","HT"]},
    {"subject": "Spanish", "classmark" : "PC"},
    {"subject": "Veterinary Medicine", "classmark" : "SF"},
]

# manual creating of dictionary inside a list with datas for creating a CSV with classmark and location
classmark_location_data = [
    {"classmark": "A", "location" : "Middle floor"}, 
    {"classmark": "AA", "location" : "Middle floor"}, 
    {"classmark": "AB", "location" : "Middle floor"}, 
    {"classmark": "AC", "location" : "Middle floor"}, 
    {"classmark": "AD", "location" : "Middle floor"}, 
    {"classmark": "AE", "location" : "Middle floor"}, 
    {"classmark": "AF", "location" : "Middle floor"}, 
    {"classmark": "AG", "location" : "Middle floor"}, 
    {"classmark": "AH", "location" : "Middle floor"}, 
    {"classmark": "AI", "location" : "Middle floor"}, 
    {"classmark": "AJ", "location" : "Middle floor"}, 
    {"classmark": "AK", "location" : "Middle floor"}, 
    {"classmark": "AL", "location" : "Middle floor"}, 
    {"classmark": "AM", "location" : "Middle floor"}, 
    {"classmark": "AN", "location" : "Middle floor"}, 
    {"classmark": "AO", "location" : "Middle floor"}, 
    {"classmark": "AP", "location" : "Middle floor"}, 
    {"classmark": "AQ", "location" : "Middle floor"}, 
    {"classmark": "AR", "location" : "Middle floor"}, 
    {"classmark": "AS", "location" : "Middle floor"}, 
    {"classmark": "AT", "location" : "Middle floor"}, 
    {"classmark": "AU", "location" : "Middle floor"}, 
    {"classmark": "AV", "location" : "Middle floor"}, 
    {"classmark": "AW", "location" : "Middle floor"}, 
    {"classmark": "AX", "location" : "Middle floor"}, 
    {"classmark": "AY", "location" : "Middle floor"}, 
    {"classmark": "AZ", "location" : "Middle floor"}, 
    {"classmark": "B", "location" : "Middle floor"}, 
    {"classmark": "BA", "location" : "Middle floor"}, 
    {"classmark": "BB", "location" : "Middle floor"}, 
    {"classmark": "BC", "location" : "Middle floor"}, 
    {"classmark": "BD", "location" : "Middle floor"}, 
    {"classmark": "BE", "location" : "Middle floor"}, 
    {"classmark": "BF", "location" : "Middle floor"}, 
    {"classmark": "BG", "location" : "Middle floor"}, 
    {"classmark": "BH", "location" : "Middle floor"}, 
    {"classmark": "BI", "location" : "Middle floor"}, 
    {"classmark": "BJ", "location" : "Middle floor"}, 
    {"classmark": "BK", "location" : "Middle floor"}, 
    {"classmark": "BL", "location" : "Middle floor"}, 
    {"classmark": "BM", "location" : "Middle floor"}, 
    {"classmark": "BN", "location" : "Middle floor"}, 
    {"classmark": "BO", "location" : "Middle floor"}, 
    {"classmark": "BP", "location" : "Middle floor"}, 
    {"classmark": "BQ", "location" : "Middle floor"}, 
    {"classmark": "BR", "location" : "Middle floor"}, 
    {"classmark": "BS", "location" : "Middle floor"}, 
    {"classmark": "BT", "location" : "Middle floor"}, 
    {"classmark": "BU", "location" : "Middle floor"}, 
    {"classmark": "BV", "location" : "Middle floor"}, 
    {"classmark": "BW", "location" : "Middle floor"}, 
    {"classmark": "BX", "location" : "Middle floor"}, 
    {"classmark": "BY", "location" : "Middle floor"}, 
    {"classmark": "BZ", "location" : "Middle floor"}, 
    {"classmark": "C", "location" : "Middle floor"}, 
    {"classmark": "CA", "location" : "Middle floor"}, 
    {"classmark": "CB", "location" : "Middle floor"}, 
    {"classmark": "CC", "location" : "Middle floor"}, 
    {"classmark": "CD", "location" : "Middle floor"}, 
    {"classmark": "CE", "location" : "Middle floor"}, 
    {"classmark": "CF", "location" : "Middle floor"}, 
    {"classmark": "CG", "location" : "Middle floor"}, 
    {"classmark": "CH", "location" : "Middle floor"}, 
    {"classmark": "CI", "location" : "Middle floor"}, 
    {"classmark": "CJ", "location" : "Middle floor"}, 
    {"classmark": "CK", "location" : "Middle floor"}, 
    {"classmark": "CL", "location" : "Middle floor"}, 
    {"classmark": "CM", "location" : "Middle floor"}, 
    {"classmark": "CN", "location" : "Middle floor"}, 
    {"classmark": "CO", "location" : "Middle floor"}, 
    {"classmark": "CP", "location" : "Middle floor"}, 
    {"classmark": "CQ", "location" : "Middle floor"}, 
    {"classmark": "CR", "location" : "Middle floor"}, 
    {"classmark": "CS", "location" : "Middle floor"}, 
    {"classmark": "CT", "location" : "Middle floor"}, 
    {"classmark": "CU", "location" : "Middle floor"}, 
    {"classmark": "CV", "location" : "Middle floor"}, 
    {"classmark": "CW", "location" : "Middle floor"}, 
    {"classmark": "CX", "location" : "Middle floor"}, 
    {"classmark": "CY", "location" : "Middle floor"}, 
    {"classmark": "CZ", "location" : "Middle floor"},
    {"classmark": "D", "location" : "Middle floor"}, 
    {"classmark": "DA", "location" : "Middle floor"}, 
    {"classmark": "DB", "location" : "Middle floor"}, 
    {"classmark": "DC", "location" : "Middle floor"}, 
    {"classmark": "DD", "location" : "Middle floor"}, 
    {"classmark": "DE", "location" : "Middle floor"}, 
    {"classmark": "DF", "location" : "Middle floor"}, 
    {"classmark": "DG", "location" : "Middle floor"}, 
    {"classmark": "DH", "location" : "Middle floor"}, 
    {"classmark": "DI", "location" : "Middle floor"}, 
    {"classmark": "DJ", "location" : "Middle floor"}, 
    {"classmark": "DK", "location" : "Middle floor"}, 
    {"classmark": "DL", "location" : "Middle floor"}, 
    {"classmark": "DM", "location" : "Middle floor"}, 
    {"classmark": "DN", "location" : "Middle floor"}, 
    {"classmark": "DO", "location" : "Middle floor"}, 
    {"classmark": "DP", "location" : "Middle floor"}, 
    {"classmark": "DQ", "location" : "Middle floor"}, 
    {"classmark": "DR", "location" : "Middle floor"}, 
    {"classmark": "DS", "location" : "Middle floor"}, 
    # new floor
    {"classmark": "DT", "location" : "Top floor bottom left"}, 
    {"classmark": "DU", "location" : "Top floor bottom left"}, 
    {"classmark": "DV", "location" : "Top floor bottom left"}, 
    {"classmark": "DW", "location" : "Top floor bottom left"}, 
    {"classmark": "DX", "location" : "Top floor bottom left"}, 
    {"classmark": "DY", "location" : "Top floor bottom left"}, 
    {"classmark": "DZ", "location" : "Top floor bottom left"}, 
    {"classmark": "E", "location" : "Top floor bottom left"}, 
    {"classmark": "EA", "location" : "Top floor bottom left"}, 
    {"classmark": "EB", "location" : "Top floor bottom left"}, 
    {"classmark": "EC", "location" : "Top floor bottom left"}, 
    {"classmark": "ED", "location" : "Top floor bottom left"}, 
    {"classmark": "EE", "location" : "Top floor bottom left"}, 
    {"classmark": "EF", "location" : "Top floor bottom left"}, 
    {"classmark": "EG", "location" : "Top floor bottom left"}, 
    {"classmark": "EH", "location" : "Top floor bottom left"}, 
    {"classmark": "EI", "location" : "Top floor bottom left"}, 
    {"classmark": "EJ", "location" : "Top floor bottom left"}, 
    {"classmark": "EK", "location" : "Top floor bottom left"}, 
    {"classmark": "EL", "location" : "Top floor bottom left"}, 
    {"classmark": "EM", "location" : "Top floor bottom left"}, 
    {"classmark": "EN", "location" : "Top floor bottom left"}, 
    {"classmark": "EO", "location" : "Top floor bottom left"}, 
    {"classmark": "EP", "location" : "Top floor bottom left"}, 
    {"classmark": "EQ", "location" : "Top floor bottom left"}, 
    {"classmark": "ER", "location" : "Top floor bottom left"}, 
    {"classmark": "ES", "location" : "Top floor bottom left"}, 
    {"classmark": "ET", "location" : "Top floor bottom left"}, 
    {"classmark": "EU", "location" : "Top floor bottom left"}, 
    {"classmark": "EV", "location" : "Top floor bottom left"}, 
    {"classmark": "EW", "location" : "Top floor bottom left"}, 
    {"classmark": "EX", "location" : "Top floor bottom left"}, 
    {"classmark": "EY", "location" : "Top floor bottom left"}, 
    {"classmark": "EZ", "location" : "Top floor bottom left"}, 
    {"classmark": "F", "location" : "Top floor bottom left"}, 
    {"classmark": "FA", "location" : "Top floor bottom left"}, 
    {"classmark": "FB", "location" : "Top floor bottom left"}, 
    {"classmark": "FC", "location" : "Top floor bottom left"}, 
    {"classmark": "FD", "location" : "Top floor bottom left"}, 
    {"classmark": "FE", "location" : "Top floor bottom left"}, 
    {"classmark": "FF", "location" : "Top floor bottom left"}, 
    {"classmark": "FG", "location" : "Top floor bottom left"}, 
    {"classmark": "FH", "location" : "Top floor bottom left"}, 
    {"classmark": "FI", "location" : "Top floor bottom left"}, 
    {"classmark": "FJ", "location" : "Top floor bottom left"}, 
    {"classmark": "FK", "location" : "Top floor bottom left"}, 
    {"classmark": "FL", "location" : "Top floor bottom left"}, 
    {"classmark": "FM", "location" : "Top floor bottom left"}, 
    {"classmark": "FN", "location" : "Top floor bottom left"}, 
    {"classmark": "FO", "location" : "Top floor bottom left"}, 
    {"classmark": "FP", "location" : "Top floor bottom left"}, 
    {"classmark": "FQ", "location" : "Top floor bottom left"}, 
    {"classmark": "FR", "location" : "Top floor bottom left"}, 
    {"classmark": "FS", "location" : "Top floor bottom left"}, 
    {"classmark": "FT", "location" : "Top floor bottom left"}, 
    {"classmark": "FU", "location" : "Top floor bottom left"}, 
    {"classmark": "FV", "location" : "Top floor bottom left"}, 
    {"classmark": "FW", "location" : "Top floor bottom left"}, 
    {"classmark": "FX", "location" : "Top floor bottom left"}, 
    {"classmark": "FY", "location" : "Top floor bottom left"}, 
    {"classmark": "FZ", "location" : "Top floor bottom left"},
    {"classmark": "G", "location" : "Top floor bottom left"}, 
    {"classmark": "GA", "location" : "Top floor bottom left"}, 
    {"classmark": "GB", "location" : "Top floor bottom left"}, 
    {"classmark": "GC", "location" : "Top floor bottom left"}, 
    {"classmark": "GD", "location" : "Top floor bottom left"}, 
    {"classmark": "GE", "location" : "Top floor bottom left"}, 
    {"classmark": "GF", "location" : "Top floor bottom left"}, 
    {"classmark": "GG", "location" : "Top floor bottom left"}, 
    {"classmark": "GH", "location" : "Top floor bottom left"}, 
    {"classmark": "GI", "location" : "Top floor bottom left"}, 
    {"classmark": "GJ", "location" : "Top floor bottom left"}, 
    {"classmark": "GK", "location" : "Top floor bottom left"}, 
    {"classmark": "GL", "location" : "Top floor bottom left"}, 
    {"classmark": "GM", "location" : "Top floor bottom left"}, 
    {"classmark": "GN", "location" : "Top floor bottom left"}, 
    {"classmark": "GO", "location" : "Top floor bottom left"}, 
    {"classmark": "GP", "location" : "Top floor bottom left"}, 
    {"classmark": "GQ", "location" : "Top floor bottom left"}, 
    {"classmark": "GR", "location" : "Top floor bottom left"}, 
    {"classmark": "GS", "location" : "Top floor bottom left"}, 
    {"classmark": "GT", "location" : "Top floor bottom left"}, 
    {"classmark": "GU", "location" : "Top floor bottom left"}, 
    {"classmark": "GV", "location" : "Top floor bottom left"}, 
    {"classmark": "GW", "location" : "Top floor bottom left"}, 
    {"classmark": "GX", "location" : "Top floor bottom left"}, 
    {"classmark": "GY", "location" : "Top floor bottom left"}, 
    {"classmark": "GZ", "location" : "Top floor bottom left"}, 
    {"classmark": "H", "location" : "Top floor bottom left"}, 
    {"classmark": "HA", "location" : "Top floor bottom left"}, 
    {"classmark": "HB", "location" : "Top floor bottom left"}, 
    {"classmark": "HC", "location" : "Top floor bottom left"}, 
    {"classmark": "HD", "location" : "Top floor bottom left"}, 
    {"classmark": "HE", "location" : "Top floor bottom left"}, 
    {"classmark": "HF", "location" : "Top floor bottom left"}, 
    {"classmark": "HG", "location" : "Top floor bottom left"}, 
    {"classmark": "HH", "location" : "Top floor bottom left"}, 
    {"classmark": "HI", "location" : "Top floor bottom left"}, 
    {"classmark": "HJ", "location" : "Top floor bottom left"}, 
    # different corner top floor
    {"classmark": "HM", "location" : "Top floor top left"}, 
    {"classmark": "HN", "location" : "Top floor top left"}, 
    {"classmark": "HO", "location" : "Top floor top left"}, 
    {"classmark": "HP", "location" : "Top floor top left"}, 
    {"classmark": "HQ", "location" : "Top floor top left"}, 
    {"classmark": "HR", "location" : "Top floor top left"}, 
    {"classmark": "HS", "location" : "Top floor top left"}, 
    {"classmark": "HT", "location" : "Top floor top left"}, 
    {"classmark": "HU", "location" : "Top floor top left"}, 
    {"classmark": "HV", "location" : "Top floor top left"}, 
    {"classmark": "HW", "location" : "Top floor top left"}, 
    {"classmark": "HX", "location" : "Top floor top left"}, 
    {"classmark": "HY", "location" : "Top floor top left"}, 
    {"classmark": "HZ", "location" : "Top floor top left"}, 
    {"classmark": "I", "location" : "Top floor top left"}, 
    {"classmark": "IA", "location" : "Top floor top left"}, 
    {"classmark": "IB", "location" : "Top floor top left"}, 
    {"classmark": "IC", "location" : "Top floor top left"}, 
    {"classmark": "ID", "location" : "Top floor top left"}, 
    {"classmark": "IE", "location" : "Top floor top left"}, 
    {"classmark": "IF", "location" : "Top floor top left"}, 
    {"classmark": "IG", "location" : "Top floor top left"}, 
    {"classmark": "IH", "location" : "Top floor top left"}, 
    {"classmark": "II", "location" : "Top floor top left"}, 
    {"classmark": "IJ", "location" : "Top floor top left"}, 
    {"classmark": "IK", "location" : "Top floor top left"}, 
    {"classmark": "IL", "location" : "Top floor top left"}, 
    {"classmark": "IM", "location" : "Top floor top left"}, 
    {"classmark": "IN", "location" : "Top floor top left"}, 
    {"classmark": "IO", "location" : "Top floor top left"}, 
    {"classmark": "IP", "location" : "Top floor top left"}, 
    {"classmark": "IQ", "location" : "Top floor top left"}, 
    {"classmark": "IR", "location" : "Top floor top left"}, 
    {"classmark": "IS", "location" : "Top floor top left"}, 
    {"classmark": "IT", "location" : "Top floor top left"}, 
    {"classmark": "IU", "location" : "Top floor top left"}, 
    {"classmark": "IV", "location" : "Top floor top left"}, 
    {"classmark": "IW", "location" : "Top floor top left"}, 
    {"classmark": "IX", "location" : "Top floor top left"}, 
    {"classmark": "IY", "location" : "Top floor top left"}, 
    {"classmark": "IZ", "location" : "Top floor top left"},
    {"classmark": "J", "location" : "Top floor top left"}, 
    {"classmark": "JA", "location" : "Top floor top left"}, 
    {"classmark": "JB", "location" : "Top floor top left"}, 
    {"classmark": "JC", "location" : "Top floor top left"}, 
    {"classmark": "JD", "location" : "Top floor top left"}, 
    {"classmark": "JE", "location" : "Top floor top left"}, 
    {"classmark": "JF", "location" : "Top floor top left"}, 
    {"classmark": "JG", "location" : "Top floor top left"}, 
    {"classmark": "JH", "location" : "Top floor top left"}, 
    {"classmark": "JI", "location" : "Top floor top left"}, 
    {"classmark": "JJ", "location" : "Top floor top left"}, 
    {"classmark": "JK", "location" : "Top floor top left"}, 
    {"classmark": "JL", "location" : "Top floor top left"}, 
    {"classmark": "JM", "location" : "Top floor top left"}, 
    {"classmark": "JN", "location" : "Top floor top left"}, 
    {"classmark": "JO", "location" : "Top floor top left"}, 
    {"classmark": "JP", "location" : "Top floor top left"}, 
    {"classmark": "JQ", "location" : "Top floor top left"}, 
    {"classmark": "JR", "location" : "Top floor top left"}, 
    {"classmark": "JS", "location" : "Top floor top left"}, 
    {"classmark": "JT", "location" : "Top floor top left"}, 
    {"classmark": "JU", "location" : "Top floor top left"}, 
    {"classmark": "JV", "location" : "Top floor top left"}, 
    {"classmark": "JW", "location" : "Top floor top left"}, 
    {"classmark": "JX", "location" : "Top floor top left"}, 
    # ground floor
    {"classmark": "JX", "location" : "Bottom floor"}, 
    {"classmark": "JY", "location" : "Bottom floor"}, 
    {"classmark": "JZ", "location" : "Bottom floor"}, 
    {"classmark": "K", "location" : "Bottom floor"}, 
    {"classmark": "KA", "location" : "Bottom floor"}, 
    {"classmark": "KB", "location" : "Bottom floor"}, 
    {"classmark": "KC", "location" : "Bottom floor"}, 
    {"classmark": "KD", "location" : "Bottom floor"}, 
    {"classmark": "KE", "location" : "Bottom floor"}, 
    {"classmark": "KF", "location" : "Bottom floor"}, 
    {"classmark": "KG", "location" : "Bottom floor"}, 
    {"classmark": "KH", "location" : "Bottom floor"}, 
    {"classmark": "KI", "location" : "Bottom floor"}, 
    {"classmark": "KJ", "location" : "Bottom floor"}, 
    {"classmark": "KK", "location" : "Bottom floor"}, 
    {"classmark": "KL", "location" : "Bottom floor"}, 
    {"classmark": "KM", "location" : "Bottom floor"}, 
    {"classmark": "KN", "location" : "Bottom floor"}, 
    {"classmark": "KO", "location" : "Bottom floor"}, 
    {"classmark": "KP", "location" : "Bottom floor"}, 
    {"classmark": "KQ", "location" : "Bottom floor"}, 
    {"classmark": "KR", "location" : "Bottom floor"}, 
    {"classmark": "KS", "location" : "Bottom floor"}, 
    {"classmark": "KT", "location" : "Bottom floor"}, 
    {"classmark": "KU", "location" : "Bottom floor"}, 
    {"classmark": "KV", "location" : "Bottom floor"}, 
    {"classmark": "KW", "location" : "Bottom floor"}, 
    {"classmark": "KX", "location" : "Bottom floor"}, 
    {"classmark": "KY", "location" : "Bottom floor"}, 
    {"classmark": "KZ", "location" : "Bottom floor"},   
    # top floor top-left
    {"classmark": "L", "location" : "Top floor top left"}, 
    {"classmark": "LA", "location" : "Top floor top left"}, 
    {"classmark": "LB", "location" : "Top floor top left"}, 
    {"classmark": "LC", "location" : "Top floor top left"}, 
    {"classmark": "LD", "location" : "Top floor top left"}, 
    {"classmark": "LE", "location" : "Top floor top left"}, 
    {"classmark": "LF", "location" : "Top floor top left"}, 
    {"classmark": "LG", "location" : "Top floor top left"}, 
    {"classmark": "LH", "location" : "Top floor top left"}, 
    {"classmark": "LI", "location" : "Top floor top left"}, 
    {"classmark": "LJ", "location" : "Top floor top left"}, 
    {"classmark": "LK", "location" : "Top floor top left"}, 
    {"classmark": "LL", "location" : "Top floor top left"}, 
    {"classmark": "LM", "location" : "Top floor top left"}, 
    {"classmark": "LN", "location" : "Top floor top left"}, 
    {"classmark": "LO", "location" : "Top floor top left"}, 
    {"classmark": "LP", "location" : "Top floor top left"}, 
    {"classmark": "LQ", "location" : "Top floor top left"}, 
    {"classmark": "LR", "location" : "Top floor top left"}, 
    {"classmark": "LS", "location" : "Top floor top left"}, 
    {"classmark": "LT", "location" : "Top floor top left"}, 
    {"classmark": "LU", "location" : "Top floor top left"}, 
    {"classmark": "LV", "location" : "Top floor top left"}, 
    {"classmark": "LW", "location" : "Top floor top left"}, 
    {"classmark": "LX", "location" : "Top floor top left"}, 
    {"classmark": "LY", "location" : "Top floor top left"}, 
    {"classmark": "LZ", "location" : "Top floor top left"}, 
    {"classmark": "M", "location" : "Top floor top left"}, 
    {"classmark": "MA", "location" : "Top floor top left"}, 
    {"classmark": "MB", "location" : "Top floor top left"}, 
    {"classmark": "MC", "location" : "Top floor top left"}, 
    {"classmark": "MD", "location" : "Top floor top left"}, 
    {"classmark": "ME", "location" : "Top floor top left"}, 
    {"classmark": "MF", "location" : "Top floor top left"}, 
    {"classmark": "MG", "location" : "Top floor top left"}, 
    {"classmark": "MH", "location" : "Top floor top left"}, 
    {"classmark": "MI", "location" : "Top floor top left"}, 
    {"classmark": "MJ", "location" : "Top floor top left"}, 
    {"classmark": "MK", "location" : "Top floor top left"}, 
    {"classmark": "ML", "location" : "Top floor top left"}, 
    {"classmark": "MM", "location" : "Top floor top left"}, 
    {"classmark": "MN", "location" : "Top floor top left"}, 
    {"classmark": "MO", "location" : "Top floor top left"}, 
    {"classmark": "MP", "location" : "Top floor top left"}, 
    {"classmark": "MQ", "location" : "Top floor top left"}, 
    {"classmark": "MR", "location" : "Top floor top left"}, 
    {"classmark": "MS", "location" : "Top floor top left"}, 
    {"classmark": "MT", "location" : "Top floor top left"}, 
    {"classmark": "MU", "location" : "Top floor top left"}, 
    {"classmark": "MV", "location" : "Top floor top left"}, 
    {"classmark": "MW", "location" : "Top floor top left"}, 
    {"classmark": "MX", "location" : "Top floor top left"}, 
    {"classmark": "MY", "location" : "Top floor top left"}, 
    {"classmark": "MZ", "location" : "Top floor top left"},
    {"classmark": "N", "location" : "Top floor top left"}, 
    {"classmark": "NA", "location" : "Top floor top left"}, 
    {"classmark": "NB", "location" : "Top floor top left"}, 
    {"classmark": "NC", "location" : "Top floor top left"}, 
    {"classmark": "ND", "location" : "Top floor top left"}, 
    {"classmark": "NE", "location" : "Top floor top left"}, 
    {"classmark": "NF", "location" : "Top floor top left"}, 
    {"classmark": "NG", "location" : "Top floor top left"}, 
    {"classmark": "NH", "location" : "Top floor top left"}, 
    {"classmark": "NI", "location" : "Top floor top left"}, 
    {"classmark": "NJ", "location" : "Top floor top left"}, 
    {"classmark": "NK", "location" : "Top floor top left"}, 
    {"classmark": "NL", "location" : "Top floor top left"}, 
    {"classmark": "NM", "location" : "Top floor top left"}, 
    {"classmark": "NN", "location" : "Top floor top left"}, 
    {"classmark": "NO", "location" : "Top floor top left"}, 
    {"classmark": "NP", "location" : "Top floor top left"}, 
    {"classmark": "NQ", "location" : "Top floor top left"}, 
    {"classmark": "NR", "location" : "Top floor top left"}, 
    {"classmark": "NS", "location" : "Top floor top left"}, 
    {"classmark": "NT", "location" : "Top floor top left"}, 
    {"classmark": "NU", "location" : "Top floor top left"}, 
    {"classmark": "NV", "location" : "Top floor top left"}, 
    {"classmark": "NW", "location" : "Top floor top left"}, 
    {"classmark": "NX", "location" : "Top floor top left"}, 
    # top floor top-right
    {"classmark": "P", "location" : "Top floor top right"}, 
    {"classmark": "PA", "location" : "Top floor top right"}, 
    {"classmark": "PB", "location" : "Top floor top right"}, 
    {"classmark": "PC", "location" : "Top floor top right"}, 
    {"classmark": "PD", "location" : "Top floor top right"}, 
    {"classmark": "PE", "location" : "Top floor top right"}, 
    {"classmark": "PF", "location" : "Top floor top right"}, 
    {"classmark": "PG", "location" : "Top floor top right"}, 
    {"classmark": "PH", "location" : "Top floor top right"}, 
    {"classmark": "PI", "location" : "Top floor top right"}, 
    {"classmark": "PJ", "location" : "Top floor top right"}, 
    {"classmark": "PK", "location" : "Top floor top right"}, 
    {"classmark": "PL", "location" : "Top floor top right"}, 
    {"classmark": "PM", "location" : "Top floor top right"}, 
    {"classmark": "PN", "location" : "Top floor top right"}, 
    {"classmark": "PO", "location" : "Top floor top right"}, 
    {"classmark": "PP", "location" : "Top floor top right"}, 
    {"classmark": "PQ", "location" : "Top floor top right"}, 
    {"classmark": "PR", "location" : "Top floor top right"}, 
    {"classmark": "PS", "location" : "Top floor top right"}, 
    {"classmark": "PT", "location" : "Top floor top right"}, 
    {"classmark": "PU", "location" : "Top floor top right"}, 
    {"classmark": "PV", "location" : "Top floor top right"}, 
    {"classmark": "PW", "location" : "Top floor top right"}, 
    {"classmark": "PX", "location" : "Top floor top right"}, 
    {"classmark": "PY", "location" : "Top floor top right"}, 
    {"classmark": "PZ", "location" : "Top floor top right"},
    # top floor bottom right
    {"classmark": "Q", "location" : "Top floor bottom right"}, 
    {"classmark": "QA", "location" : "Top floor bottom right"}, 
    {"classmark": "QB", "location" : "Top floor bottom right"}, 
    {"classmark": "QC", "location" : "Top floor bottom right"}, 
    {"classmark": "QD", "location" : "Top floor bottom right"}, 
    {"classmark": "QE", "location" : "Top floor bottom right"}, 
    {"classmark": "QF", "location" : "Top floor bottom right"}, 
    {"classmark": "QG", "location" : "Top floor bottom right"}, 
    {"classmark": "QH", "location" : "Top floor bottom right"}, 
    {"classmark": "QI", "location" : "Top floor bottom right"}, 
    {"classmark": "QJ", "location" : "Top floor bottom right"}, 
    {"classmark": "QK", "location" : "Top floor bottom right"}, 
    {"classmark": "QL", "location" : "Top floor bottom right"}, 
    {"classmark": "QM", "location" : "Top floor bottom right"}, 
    {"classmark": "QN", "location" : "Top floor bottom right"}, 
    {"classmark": "QO", "location" : "Top floor bottom right"}, 
    {"classmark": "QP", "location" : "Top floor bottom right"}, 
    {"classmark": "QQ", "location" : "Top floor bottom right"}, 
    {"classmark": "QR", "location" : "Top floor bottom right"}, 
    {"classmark": "QS", "location" : "Top floor bottom right"}, 
    {"classmark": "QT", "location" : "Top floor bottom right"}, 
    {"classmark": "QU", "location" : "Top floor bottom right"}, 
    {"classmark": "QV", "location" : "Top floor bottom right"}, 
    {"classmark": "QW", "location" : "Top floor bottom right"}, 
    {"classmark": "QX", "location" : "Top floor bottom right"}, 
    {"classmark": "QY", "location" : "Top floor bottom right"}, 
    {"classmark": "QZ", "location" : "Top floor bottom right"}, 
    {"classmark": "R", "location" : "Top floor bottom right"}, 
    {"classmark": "RA", "location" : "Top floor bottom right"}, 
    {"classmark": "RB", "location" : "Top floor bottom right"}, 
    {"classmark": "RC", "location" : "Top floor bottom right"}, 
    {"classmark": "RD", "location" : "Top floor bottom right"}, 
    {"classmark": "RE", "location" : "Top floor bottom right"}, 
    {"classmark": "RF", "location" : "Top floor bottom right"}, 
    {"classmark": "RG", "location" : "Top floor bottom right"}, 
    {"classmark": "RH", "location" : "Top floor bottom right"}, 
    {"classmark": "RI", "location" : "Top floor bottom right"}, 
    {"classmark": "RJ", "location" : "Top floor bottom right"}, 
    {"classmark": "RK", "location" : "Top floor bottom right"}, 
    {"classmark": "RL", "location" : "Top floor bottom right"}, 
    {"classmark": "RM", "location" : "Top floor bottom right"}, 
    {"classmark": "RN", "location" : "Top floor bottom right"}, 
    {"classmark": "RO", "location" : "Top floor bottom right"}, 
    {"classmark": "RP", "location" : "Top floor bottom right"}, 
    {"classmark": "RQ", "location" : "Top floor bottom right"}, 
    {"classmark": "RR", "location" : "Top floor bottom right"}, 
    {"classmark": "RS", "location" : "Top floor bottom right"}, 
    {"classmark": "RT", "location" : "Top floor bottom right"}, 
    {"classmark": "RU", "location" : "Top floor bottom right"}, 
    {"classmark": "RV", "location" : "Top floor bottom right"}, 
    {"classmark": "RW", "location" : "Top floor bottom right"}, 
    {"classmark": "RX", "location" : "Top floor bottom right"}, 
    {"classmark": "RY", "location" : "Top floor bottom right"}, 
    {"classmark": "RZ", "location" : "Top floor bottom right"}, 
    {"classmark": "S", "location" : "Top floor bottom right"}, 
    {"classmark": "SA", "location" : "Top floor bottom right"}, 
    {"classmark": "SB", "location" : "Top floor bottom right"}, 
    {"classmark": "SC", "location" : "Top floor bottom right"}, 
    {"classmark": "SD", "location" : "Top floor bottom right"}, 
    {"classmark": "SE", "location" : "Top floor bottom right"}, 
    {"classmark": "SF", "location" : "Top floor bottom right"}, 
    {"classmark": "SG", "location" : "Top floor bottom right"}, 
    {"classmark": "SH", "location" : "Top floor bottom right"}, 
    {"classmark": "SI", "location" : "Top floor bottom right"}, 
    {"classmark": "SJ", "location" : "Top floor bottom right"}, 
    {"classmark": "SK", "location" : "Top floor bottom right"}, 
    {"classmark": "SL", "location" : "Top floor bottom right"}, 
    {"classmark": "SM", "location" : "Top floor bottom right"}, 
    {"classmark": "SN", "location" : "Top floor bottom right"}, 
    {"classmark": "SO", "location" : "Top floor bottom right"}, 
    {"classmark": "SP", "location" : "Top floor bottom right"}, 
    {"classmark": "SQ", "location" : "Top floor bottom right"}, 
    {"classmark": "SR", "location" : "Top floor bottom right"}, 
    {"classmark": "SS", "location" : "Top floor bottom right"}, 
    {"classmark": "ST", "location" : "Top floor bottom right"}, 
    {"classmark": "SU", "location" : "Top floor bottom right"}, 
    {"classmark": "SV", "location" : "Top floor bottom right"}, 
    {"classmark": "SW", "location" : "Top floor bottom right"}, 
    {"classmark": "SX", "location" : "Top floor bottom right"}, 
    {"classmark": "SY", "location" : "Top floor bottom right"}, 
    {"classmark": "SZ", "location" : "Top floor bottom right"}, 
    {"classmark": "T", "location" : "Top floor bottom right"}, 
    {"classmark": "TA", "location" : "Top floor bottom right"}, 
    {"classmark": "TB", "location" : "Top floor bottom right"}, 
    {"classmark": "TC", "location" : "Top floor bottom right"}, 
    {"classmark": "TD", "location" : "Top floor bottom right"}, 
    {"classmark": "TE", "location" : "Top floor bottom right"}, 
    {"classmark": "TF", "location" : "Top floor bottom right"}, 
    {"classmark": "TG", "location" : "Top floor bottom right"}, 
    {"classmark": "TH", "location" : "Top floor bottom right"}, 
    {"classmark": "TI", "location" : "Top floor bottom right"}, 
    {"classmark": "TJ", "location" : "Top floor bottom right"}, 
    {"classmark": "TK", "location" : "Top floor bottom right"}, 
    {"classmark": "TL", "location" : "Top floor bottom right"}, 
    {"classmark": "TM", "location" : "Top floor bottom right"}, 
    {"classmark": "TN", "location" : "Top floor bottom right"}, 
    {"classmark": "TO", "location" : "Top floor bottom right"}, 
    {"classmark": "TP", "location" : "Top floor bottom right"}, 
    {"classmark": "TQ", "location" : "Top floor bottom right"}, 
    {"classmark": "TR", "location" : "Top floor bottom right"}, 
    {"classmark": "TS", "location" : "Top floor bottom right"}, 
    {"classmark": "TT", "location" : "Top floor bottom right"}, 
    {"classmark": "TU", "location" : "Top floor bottom right"}, 
    {"classmark": "TV", "location" : "Top floor bottom right"}, 
    {"classmark": "TW", "location" : "Top floor bottom right"}, 
    {"classmark": "TX", "location" : "Top floor bottom right"}, 
    {"classmark": "TY", "location" : "Top floor bottom right"}, 
    {"classmark": "TZ", "location" : "Top floor bottom right"}, 
    {"classmark": "U", "location" : "Top floor bottom right"}, 
    {"classmark": "UA", "location" : "Top floor bottom right"}, 
    {"classmark": "UB", "location" : "Top floor bottom right"}, 
    {"classmark": "UC", "location" : "Top floor bottom right"}, 
    {"classmark": "UD", "location" : "Top floor bottom right"}, 
    {"classmark": "UE", "location" : "Top floor bottom right"}, 
    {"classmark": "UF", "location" : "Top floor bottom right"}, 
    {"classmark": "UG", "location" : "Top floor bottom right"}, 
    {"classmark": "UH", "location" : "Top floor bottom right"}, 
    {"classmark": "UI", "location" : "Top floor bottom right"}, 
    {"classmark": "UJ", "location" : "Top floor bottom right"}, 
    {"classmark": "UK", "location" : "Top floor bottom right"}, 
    {"classmark": "UL", "location" : "Top floor bottom right"}, 
    {"classmark": "UM", "location" : "Top floor bottom right"}, 
    {"classmark": "UN", "location" : "Top floor bottom right"}, 
    {"classmark": "UO", "location" : "Top floor bottom right"}, 
    {"classmark": "UP", "location" : "Top floor bottom right"}, 
    {"classmark": "UQ", "location" : "Top floor bottom right"}, 
    {"classmark": "UR", "location" : "Top floor bottom right"}, 
    {"classmark": "US", "location" : "Top floor bottom right"}, 
    {"classmark": "UT", "location" : "Top floor bottom right"}, 
    {"classmark": "UU", "location" : "Top floor bottom right"}, 
    {"classmark": "UV", "location" : "Top floor bottom right"}, 
    {"classmark": "UW", "location" : "Top floor bottom right"}, 
    {"classmark": "UX", "location" : "Top floor bottom right"}, 
    {"classmark": "UY", "location" : "Top floor bottom right"}, 
    {"classmark": "UZ", "location" : "Top floor bottom right"}, 
    {"classmark": "V", "location" : "Top floor bottom right"}, 
]

# CSV headers
subject_classmark_header = ["subject", "classmark"]
classmark_location_header = ["classmark", "location"]

# function to create CSV file
def create_csv(fileName, dataList, header):
    with open(f'{fileName}', 'w', newline="") as new_file:
        dataKeys = dataList[0].keys()
        writer = csv.writer(new_file)
        writer.writerow(header)
        writer = csv.DictWriter(new_file, fieldnames= dataKeys)
        for values in dataList:    
            writer.writerow(values)            

# function to read CSV file
def read_csv(fileName):
    with open(f'{fileName}', 'r') as file_to_read:
        datas = csv.reader(file_to_read)
        storeData = []        
        for data in datas:
            storeData.append(data)    
        return storeData;

# creating 2 files with CSV then storing it on variables
subject_and_classmark = create_csv("subject_classmark.csv", subject_classmark_data, subject_classmark_header)
Classmark_and_location = create_csv("classmark_location.csv", classmark_location_data, classmark_location_header)